server:
  port: 8002
---
spring:
  application:
    name: springcloud-config-server
  profiles: pro
  cloud:
    config:
      server:
        git:
          #这是其他项目配置文件的git仓库地址
          uri: https://github.com/grandtang/spring-cloud-configs
          searchPaths: '{application}'
eureka:
  client:
    service-url:
      #注册服务到eureka上，记住这里要加上eureka-server的用户名和密码
      defaultZone: http://spark-slaves-01:8001/eureka,http://spark-master-01:8001/eureka
#      defaultZone: http://root:booszy@localhost:8001/eureka
  instance:
    prefer-ip-address: true
    #可能比较长，复制的时候请写在一行
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    appname: springcloud-config-server
#security:
#  basic:
#    enabled: true
#  user:
#    #这是config-server的用户名和密码
#    name: root
#    password: booszy

---
spring:
  application:
    name: springcloud-config-server
  profiles: dev
  cloud:
    config:
      server:
        git:
          #这是其他项目配置文件的git仓库地址
          uri: https://github.com/grandtang/spring-cloud-configs
          searchPaths: '{application}'
eureka:
  client:
    service-url:
      #注册服务到eureka上，记住这里要加上eureka-server的用户名和密码
      defaultZone: http://localhost:8001/eureka
#      defaultZone: http://root:booszy@localhost:8001/eureka
  instance:
    prefer-ip-address: true
    #可能比较长，复制的时候请写在一行
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    appname: springcloud-config-server
#security:
#  basic:
#    enabled: true
#  user:
#    #这是config-server的用户名和密码
#    name: root
#    password: booszy